defmodule EventSales.Repo.Migrations.Slice16CsvImportDryRun do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_csv_import_rows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :row_number, :bigint, null: false
      add :raw_data, :map, null: false, default: %{}
      add :normalized_data, :map, null: false, default: %{}
      add :status, :text, null: false
      add :error_messages, {:array, :text}, null: false, default: []
      add :external_order_number, :text
      add :external_line_key, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :csv_import_batch_id, :uuid, null: false
    end

    create index(:ingestion_csv_import_rows, [:csv_import_batch_id, :row_number],
             name: "ingestion_csv_import_rows_unique_batch_row_idx",
             unique: true
           )

    create index(:ingestion_csv_import_rows, [:external_line_key],
             name: "ingestion_csv_import_rows_external_line_key_idx"
           )

    create index(:ingestion_csv_import_rows, [:external_order_number],
             name: "ingestion_csv_import_rows_external_order_number_idx"
           )

    create index(:ingestion_csv_import_rows, [:status],
             name: "ingestion_csv_import_rows_status_idx"
           )

    create index(:ingestion_csv_import_rows, [:csv_import_batch_id],
             name: "ingestion_csv_import_rows_batch_id_idx"
           )

    create table(:ingestion_csv_import_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ingestion_csv_import_rows) do
      modify :csv_import_batch_id,
             references(:ingestion_csv_import_batches,
               column: :id,
               name: "ingestion_csv_import_rows_csv_import_batch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:ingestion_csv_import_batches) do
      add :source_filename, :text, null: false
      add :status, :text, null: false, default: "uploaded"
      add :row_count, :bigint, null: false, default: 0
      add :valid_count, :bigint, null: false, default: 0
      add :error_count, :bigint, null: false, default: 0
      add :duplicate_count, :bigint, null: false, default: 0
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_csv_import_batches_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :uploaded_by_user_id,
          references(:accounts_users,
            column: :id,
            name: "ingestion_csv_import_batches_uploaded_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:ingestion_csv_import_batches, [:inserted_at],
             name: "ingestion_csv_import_batches_inserted_at_idx"
           )

    create index(:ingestion_csv_import_batches, [:uploaded_by_user_id],
             name: "ingestion_csv_import_batches_uploaded_by_user_id_idx"
           )

    create index(:ingestion_csv_import_batches, [:status],
             name: "ingestion_csv_import_batches_status_idx"
           )

    create index(:ingestion_csv_import_batches, [:event_id],
             name: "ingestion_csv_import_batches_event_id_idx"
           )
  end

  def down do
    drop constraint(:ingestion_csv_import_batches, "ingestion_csv_import_batches_event_id_fkey")

    drop constraint(
           :ingestion_csv_import_batches,
           "ingestion_csv_import_batches_uploaded_by_user_id_fkey"
         )

    drop_if_exists index(:ingestion_csv_import_batches, [:event_id],
                     name: "ingestion_csv_import_batches_event_id_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_batches, [:status],
                     name: "ingestion_csv_import_batches_status_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_batches, [:uploaded_by_user_id],
                     name: "ingestion_csv_import_batches_uploaded_by_user_id_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_batches, [:inserted_at],
                     name: "ingestion_csv_import_batches_inserted_at_idx"
                   )

    alter table(:ingestion_csv_import_batches) do
      remove :uploaded_by_user_id
      remove :event_id
      remove :updated_at
      remove :inserted_at
      remove :last_error
      remove :duplicate_count
      remove :error_count
      remove :valid_count
      remove :row_count
      remove :status
      remove :source_filename
    end

    drop constraint(
           :ingestion_csv_import_rows,
           "ingestion_csv_import_rows_csv_import_batch_id_fkey"
         )

    alter table(:ingestion_csv_import_rows) do
      modify :csv_import_batch_id, :uuid
    end

    drop table(:ingestion_csv_import_batches)

    drop_if_exists index(:ingestion_csv_import_rows, [:csv_import_batch_id],
                     name: "ingestion_csv_import_rows_batch_id_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_rows, [:status],
                     name: "ingestion_csv_import_rows_status_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_rows, [:external_order_number],
                     name: "ingestion_csv_import_rows_external_order_number_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_rows, [:external_line_key],
                     name: "ingestion_csv_import_rows_external_line_key_idx"
                   )

    drop_if_exists index(:ingestion_csv_import_rows, [:csv_import_batch_id, :row_number],
                     name: "ingestion_csv_import_rows_unique_batch_row_idx"
                   )

    drop table(:ingestion_csv_import_rows)
  end
end
