defmodule EventSales.Repo.Migrations.M502bEventDimensionAggregateSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:analytics_event_dimension_aggregate_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false
      add :dimension_kind, :text, null: false
      add :woo_product_id, :bigint
      add :woo_variation_id, :bigint
      add :gross_ticket_quantity, :bigint, null: false, default: 0
      add :gross_ticket_value, :decimal, null: false, default: "0"
      add :refreshed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_event_dimension_aggregate_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :ticket_type_id,
          references(:catalog_ticket_types,
            column: :id,
            name: "analytics_event_dimension_aggregate_snapshots_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "analytics_event_dimension_aggregate_snapshots_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )
    end

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_grain_shape_check,
             check: """
               (
               (dimension_kind = 'ticket_type'
                AND ticket_type_id IS NOT NULL
                AND source_system_id IS NULL
                AND woo_product_id IS NULL
                AND woo_variation_id IS NULL)
               OR
               (dimension_kind = 'source_product'
                AND ticket_type_id IS NULL
                AND source_system_id IS NOT NULL
                AND woo_product_id IS NOT NULL
                AND woo_variation_id IS NULL)
               OR
               (dimension_kind = 'source_variation'
                AND ticket_type_id IS NULL
                AND source_system_id IS NOT NULL
                AND woo_product_id IS NOT NULL
                AND woo_variation_id IS NOT NULL)
             )

             """
           )

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_gross_ticket_quantity_check,
             check: """
               gross_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_gross_ticket_value_check,
             check: """
               gross_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_woo_product_id_check,
             check: """
               woo_product_id IS NULL OR woo_product_id > 0
             """
           )

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_woo_variation_id_check,
             check: """
               woo_variation_id IS NULL OR woo_variation_id > 0
             """
           )

    create index(:analytics_event_dimension_aggregate_snapshots, [:event_id],
             name: "analytics_event_dim_agg_snapshots_event_id_idx"
           )

    create index(
             :analytics_event_dimension_aggregate_snapshots,
             [:event_id, :currency, :ticket_type_id],
             name: "analytics_event_dim_agg_snapshots_unique_ticket_type_idx",
             unique: true,
             where: "dimension_kind = 'ticket_type'"
           )

    create index(
             :analytics_event_dimension_aggregate_snapshots,
             [:event_id, :currency, :source_system_id, :woo_product_id],
             name: "analytics_event_dim_agg_snapshots_unique_source_product_idx",
             unique: true,
             where: "dimension_kind = 'source_product'"
           )

    create index(
             :analytics_event_dimension_aggregate_snapshots,
             [:event_id, :currency, :source_system_id, :woo_product_id, :woo_variation_id],
             name: "analytics_event_dim_agg_snapshots_unique_source_variation_idx",
             unique: true,
             where: "dimension_kind = 'source_variation'"
           )
  end

  def down do
    drop_if_exists index(
                     :analytics_event_dimension_aggregate_snapshots,
                     [
                       :event_id,
                       :currency,
                       :source_system_id,
                       :woo_product_id,
                       :woo_variation_id
                     ],
                     name: "analytics_event_dim_agg_snapshots_unique_source_variation_idx"
                   )

    drop_if_exists index(
                     :analytics_event_dimension_aggregate_snapshots,
                     [:event_id, :currency, :source_system_id, :woo_product_id],
                     name: "analytics_event_dim_agg_snapshots_unique_source_product_idx"
                   )

    drop_if_exists index(
                     :analytics_event_dimension_aggregate_snapshots,
                     [:event_id, :currency, :ticket_type_id],
                     name: "analytics_event_dim_agg_snapshots_unique_ticket_type_idx"
                   )

    drop_if_exists index(:analytics_event_dimension_aggregate_snapshots, [:event_id],
                     name: "analytics_event_dim_agg_snapshots_event_id_idx"
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_woo_variation_id_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_woo_product_id_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_gross_ticket_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_gross_ticket_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_grain_shape_check
                   )

    drop constraint(
           :analytics_event_dimension_aggregate_snapshots,
           "analytics_event_dimension_aggregate_snapshots_source_system_id_fkey"
         )

    drop constraint(
           :analytics_event_dimension_aggregate_snapshots,
           "analytics_event_dimension_aggregate_snapshots_ticket_type_id_fkey"
         )

    drop constraint(
           :analytics_event_dimension_aggregate_snapshots,
           "analytics_event_dimension_aggregate_snapshots_event_id_fkey"
         )

    drop table(:analytics_event_dimension_aggregate_snapshots)
  end
end
