defmodule EventSales.Repo.Migrations.Slice88PapertrailOperationalAuditSplit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :actor_type, :text, null: false
      add :actor_user_id, :uuid
      add :actor_role, :text
      add :subject_type, :text
      add :subject_id, :text
      add :event_id, :uuid
      add :source, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :ip_hash, :text
      add :user_agent_hash, :text
      add :occurred_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:audit_logs, [:occurred_at], name: "audit_logs_occurred_at_idx")

    create index(:audit_logs, [:source], name: "audit_logs_source_idx")

    create index(:audit_logs, [:subject_type, :subject_id], name: "audit_logs_subject_idx")

    create index(:audit_logs, [:event_id], name: "audit_logs_event_id_idx")

    create index(:audit_logs, [:actor_user_id], name: "audit_logs_actor_user_id_idx")

    create index(:audit_logs, [:event_type], name: "audit_logs_event_type_idx")

    create table(:accounts_event_access_grant_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:accounts_event_access_grants,
            column: :id,
            name: "accounts_event_access_grant_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :accounts_event_access_grant_versions,
           "accounts_event_access_grant_versions_version_source_id_fkey"
         )

    drop table(:accounts_event_access_grant_versions)

    drop_if_exists index(:audit_logs, [:event_type], name: "audit_logs_event_type_idx")

    drop_if_exists index(:audit_logs, [:actor_user_id], name: "audit_logs_actor_user_id_idx")

    drop_if_exists index(:audit_logs, [:event_id], name: "audit_logs_event_id_idx")

    drop_if_exists index(:audit_logs, [:subject_type, :subject_id],
                     name: "audit_logs_subject_idx"
                   )

    drop_if_exists index(:audit_logs, [:source], name: "audit_logs_source_idx")

    drop_if_exists index(:audit_logs, [:occurred_at], name: "audit_logs_occurred_at_idx")

    drop table(:audit_logs)
  end
end
