defmodule EventSales.Repo.Migrations.M504fContributionFactEdgePredicateIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:analytics_contribution_facts, [:event_id, :currency, :effective_at],
             name: "analytics_contribution_facts_event_currency_effective_at_idx"
           )
  end

  def down do
    drop_if_exists index(:analytics_contribution_facts, [:event_id, :currency, :effective_at],
                     name: "analytics_contribution_facts_event_currency_effective_at_idx"
                   )
  end
end
