defmodule EventSales.Repo.Migrations.M504cPeriodAggregateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:analytics_event_dimension_period_aggregate_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false
      add :bucket_kind, :text, null: false
      add :bucket_start_utc, :utc_datetime_usec, null: false
      add :bucket_end_utc, :utc_datetime_usec, null: false
      add :bucket_timezone, :text, null: false
      add :dimension_kind, :text, null: false
      add :woo_product_id, :bigint
      add :woo_variation_id, :bigint
      add :gross_ticket_quantity, :bigint, null: false, default: 0
      add :gross_ticket_value, :decimal, null: false, default: "0"
      add :refund_ticket_quantity, :bigint, null: false, default: 0
      add :refund_ticket_value, :decimal, null: false, default: "0"
      add :generation_id, :uuid, null: false
      add :semantic_version, :bigint, null: false
      add :coverage_identity, :text, null: false
      add :projection_state, :text, null: false
      add :refreshed_at, :utc_datetime_usec, null: false
      add :source_watermark_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_event_dimension_period_aggregate_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :ticket_type_id,
          references(:catalog_ticket_types,
            column: :id,
            name: "analytics_event_dimension_period_aggregate_snapshots_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "analytics_event_dimension_period_aggregate_snapshots_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )
    end

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_bucket_timezone_check,
             check: """
               (
               (bucket_kind = 'utc_hour' AND bucket_timezone = 'UTC')
               OR
               (bucket_kind = 'johannesburg_day' AND bucket_timezone = 'Africa/Johannesburg')
             )

             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_bucket_bounds_check,
             check: """
               bucket_start_utc < bucket_end_utc
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_projection_state_check,
             check: """
               projection_state IN ('current', 'stale', 'refresh_pending', 'rebuilding', 'unavailable')
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_semantic_version_check,
             check: """
               semantic_version >= 1
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_grain_shape_check,
             check: """
               (
               (dimension_kind = 'ticket_type'
                AND ticket_type_id IS NOT NULL
                AND source_system_id IS NULL
                AND woo_product_id IS NULL
                AND woo_variation_id IS NULL)
               OR
               (dimension_kind = 'source_product'
                AND ticket_type_id IS NULL
                AND source_system_id IS NOT NULL
                AND woo_product_id IS NOT NULL
                AND woo_variation_id IS NULL)
               OR
               (dimension_kind = 'source_variation'
                AND ticket_type_id IS NULL
                AND source_system_id IS NOT NULL
                AND woo_product_id IS NOT NULL
                AND woo_variation_id IS NOT NULL)
             )

             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_gross_quantity_check,
             check: """
               gross_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_gross_value_check,
             check: """
               gross_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_refund_quantity_check,
             check: """
               refund_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_refund_value_check,
             check: """
               refund_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_woo_product_id_check,
             check: """
               woo_product_id IS NULL OR woo_product_id > 0
             """
           )

    create constraint(
             :analytics_event_dimension_period_aggregate_snapshots,
             :analytics_dim_period_woo_variation_id_check,
             check: """
               woo_variation_id IS NULL OR woo_variation_id > 0
             """
           )

    create index(
             :analytics_event_dimension_period_aggregate_snapshots,
             [
               :event_id,
               :currency,
               :bucket_kind,
               :bucket_start_utc,
               :bucket_end_utc,
               :ticket_type_id
             ],
             name: "analytics_dim_period_ticket_type_uidx",
             unique: true,
             where: "dimension_kind = 'ticket_type'"
           )

    create index(
             :analytics_event_dimension_period_aggregate_snapshots,
             [
               :event_id,
               :currency,
               :bucket_kind,
               :bucket_start_utc,
               :bucket_end_utc,
               :source_system_id,
               :woo_product_id
             ],
             name: "analytics_dim_period_source_product_uidx",
             unique: true,
             where: "dimension_kind = 'source_product'"
           )

    create index(
             :analytics_event_dimension_period_aggregate_snapshots,
             [
               :event_id,
               :currency,
               :bucket_kind,
               :bucket_start_utc,
               :bucket_end_utc,
               :source_system_id,
               :woo_product_id,
               :woo_variation_id
             ],
             name: "analytics_dim_period_source_variation_uidx",
             unique: true,
             where: "dimension_kind = 'source_variation'"
           )

    create table(:analytics_contribution_facts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :contribution_kind, :text, null: false
      add :source_contribution_id, :uuid, null: false
      add :currency, :text, null: false
      add :effective_at, :utc_datetime_usec, null: false
      add :woo_product_id, :bigint, null: false
      add :woo_variation_id, :bigint
      add :gross_ticket_quantity, :bigint, null: false, default: 0
      add :gross_ticket_value, :decimal, null: false, default: "0"
      add :refund_ticket_quantity, :bigint, null: false, default: 0
      add :refund_ticket_value, :decimal, null: false, default: "0"
      add :generation_id, :uuid, null: false
      add :semantic_version, :bigint, null: false
      add :coverage_identity, :text, null: false
      add :refreshed_at, :utc_datetime_usec, null: false
      add :source_watermark_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_contribution_facts_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :ticket_type_id,
          references(:catalog_ticket_types,
            column: :id,
            name: "analytics_contribution_facts_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "analytics_contribution_facts_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_gross_quantity_check,
             check: """
               gross_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_gross_value_check,
             check: """
               gross_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_refund_quantity_check,
             check: """
               refund_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_refund_value_check,
             check: """
               refund_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_woo_product_id_check,
             check: """
               woo_product_id > 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_woo_variation_id_check,
             check: """
               woo_variation_id IS NULL OR woo_variation_id > 0
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_semantic_version_check,
             check: """
               semantic_version >= 1
             """
           )

    create constraint(
             :analytics_contribution_facts,
             :analytics_contribution_facts_kind_shape_check,
             check: """
               (
               (contribution_kind = 'sale'
                AND gross_ticket_quantity > 0
                AND gross_ticket_value >= 0
                AND refund_ticket_quantity = 0
                AND refund_ticket_value = 0)
               OR
               (contribution_kind = 'refund'
                AND gross_ticket_quantity = 0
                AND gross_ticket_value = 0
                AND refund_ticket_quantity >= 0
                AND refund_ticket_value >= 0
                AND (refund_ticket_quantity > 0 OR refund_ticket_value > 0))
             )

             """
           )

    create index(:analytics_contribution_facts, [:contribution_kind, :source_contribution_id],
             name: "analytics_contribution_facts_source_identity_uidx",
             unique: true
           )

    create table(:analytics_event_period_aggregate_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false
      add :bucket_kind, :text, null: false
      add :bucket_start_utc, :utc_datetime_usec, null: false
      add :bucket_end_utc, :utc_datetime_usec, null: false
      add :bucket_timezone, :text, null: false
      add :gross_ticket_quantity, :bigint, null: false, default: 0
      add :gross_ticket_value, :decimal, null: false, default: "0"
      add :refund_ticket_quantity, :bigint, null: false, default: 0
      add :refund_ticket_value, :decimal, null: false, default: "0"
      add :generation_id, :uuid, null: false
      add :semantic_version, :bigint, null: false
      add :coverage_identity, :text, null: false
      add :projection_state, :text, null: false
      add :refreshed_at, :utc_datetime_usec, null: false
      add :source_watermark_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_event_period_aggregate_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_bucket_timezone_check,
             check: """
               (
               (bucket_kind = 'utc_hour' AND bucket_timezone = 'UTC')
               OR
               (bucket_kind = 'johannesburg_day' AND bucket_timezone = 'Africa/Johannesburg')
             )

             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_bucket_bounds_check,
             check: """
               bucket_start_utc < bucket_end_utc
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_projection_state_check,
             check: """
               projection_state IN ('current', 'stale', 'refresh_pending', 'rebuilding', 'unavailable')
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_semantic_version_check,
             check: """
               semantic_version >= 1
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_gross_quantity_check,
             check: """
               gross_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_gross_value_check,
             check: """
               gross_ticket_value >= 0
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_refund_quantity_check,
             check: """
               refund_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_period_aggregate_snapshots,
             :analytics_event_period_refund_value_check,
             check: """
               refund_ticket_value >= 0
             """
           )

    create index(
             :analytics_event_period_aggregate_snapshots,
             [:event_id, :currency, :bucket_kind, :bucket_start_utc, :bucket_end_utc],
             name: "analytics_event_period_aggregate_snapshots_identity_idx",
             unique: true
           )
  end

  def down do
    drop_if_exists index(
                     :analytics_event_period_aggregate_snapshots,
                     [:event_id, :currency, :bucket_kind, :bucket_start_utc, :bucket_end_utc],
                     name: "analytics_event_period_aggregate_snapshots_identity_idx"
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_refund_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_refund_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_gross_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_gross_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_semantic_version_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_projection_state_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_bucket_bounds_check
                   )

    drop_if_exists constraint(
                     :analytics_event_period_aggregate_snapshots,
                     :analytics_event_period_bucket_timezone_check
                   )

    drop constraint(
           :analytics_event_period_aggregate_snapshots,
           "analytics_event_period_aggregate_snapshots_event_id_fkey"
         )

    drop table(:analytics_event_period_aggregate_snapshots)

    drop_if_exists index(
                     :analytics_contribution_facts,
                     [:contribution_kind, :source_contribution_id],
                     name: "analytics_contribution_facts_source_identity_uidx"
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_kind_shape_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_semantic_version_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_woo_variation_id_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_woo_product_id_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_refund_value_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_refund_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_gross_value_check
                   )

    drop_if_exists constraint(
                     :analytics_contribution_facts,
                     :analytics_contribution_facts_gross_quantity_check
                   )

    drop constraint(
           :analytics_contribution_facts,
           "analytics_contribution_facts_source_system_id_fkey"
         )

    drop constraint(
           :analytics_contribution_facts,
           "analytics_contribution_facts_ticket_type_id_fkey"
         )

    drop constraint(:analytics_contribution_facts, "analytics_contribution_facts_event_id_fkey")

    drop table(:analytics_contribution_facts)

    drop_if_exists index(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     [
                       :event_id,
                       :currency,
                       :bucket_kind,
                       :bucket_start_utc,
                       :bucket_end_utc,
                       :source_system_id,
                       :woo_product_id,
                       :woo_variation_id
                     ],
                     name: "analytics_dim_period_source_variation_uidx"
                   )

    drop_if_exists index(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     [
                       :event_id,
                       :currency,
                       :bucket_kind,
                       :bucket_start_utc,
                       :bucket_end_utc,
                       :source_system_id,
                       :woo_product_id
                     ],
                     name: "analytics_dim_period_source_product_uidx"
                   )

    drop_if_exists index(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     [
                       :event_id,
                       :currency,
                       :bucket_kind,
                       :bucket_start_utc,
                       :bucket_end_utc,
                       :ticket_type_id
                     ],
                     name: "analytics_dim_period_ticket_type_uidx"
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_woo_variation_id_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_woo_product_id_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_refund_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_refund_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_gross_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_gross_quantity_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_grain_shape_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_semantic_version_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_projection_state_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_bucket_bounds_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_period_aggregate_snapshots,
                     :analytics_dim_period_bucket_timezone_check
                   )

    drop constraint(
           :analytics_event_dimension_period_aggregate_snapshots,
           "analytics_event_dimension_period_aggregate_snapshots_source_system_id_fkey"
         )

    drop constraint(
           :analytics_event_dimension_period_aggregate_snapshots,
           "analytics_event_dimension_period_aggregate_snapshots_ticket_type_id_fkey"
         )

    drop constraint(
           :analytics_event_dimension_period_aggregate_snapshots,
           "analytics_event_dimension_period_aggregate_snapshots_event_id_fkey"
         )

    drop table(:analytics_event_dimension_period_aggregate_snapshots)
  end
end
