defmodule EventSales.Repo.Migrations.PreM5ReadyIxTerminal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(
                     :ingestion_financial_reconciliation_runs,
                     [:event_id, :historical_sync_run_id, :finished_at],
                     name: "ingestion_fin_recon_runs_cert_lookup_idx"
                   )

    execute("""
    CREATE INDEX ingestion_fin_recon_runs_terminal_ready_ix
    ON ingestion_financial_reconciliation_runs (
      event_id,
      historical_sync_run_id,
      finished_at DESC NULLS LAST,
      inserted_at DESC,
      id DESC
    )
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS ingestion_fin_recon_runs_terminal_ready_ix
    """)

    create index(
             :ingestion_financial_reconciliation_runs,
             [:event_id, :historical_sync_run_id, :finished_at],
             name: "ingestion_fin_recon_runs_cert_lookup_idx"
           )
  end
end
