defmodule EventSales.Repo.Migrations.Vs26e2CatalogAutoApply do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:next_attempt_at, :source_system_id, :id],
                     name: "tickera_catalog_auto_apply_decisions_recovery_idx"
                   )

    create index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:next_attempt_at, :source_system_id, :id],
             name: "tickera_catalog_auto_apply_decisions_recovery_idx",
             where:
               "enqueue_state IN ('claimed', 'enqueued', 'retryable_failure') AND next_attempt_at IS NOT NULL"
           )

    alter table(:ingestion_tickera_catalog_auto_apply_decisions) do
      modify :historical_summary, :map, default: nil
      modify :action_summary, :map, default: nil
      modify :finding_summary, :map, default: nil
    end
  end

  def down do
    alter table(:ingestion_tickera_catalog_auto_apply_decisions) do
      modify :finding_summary, :map, default: %{}
      modify :action_summary, :map, default: %{}
      modify :historical_summary, :map, default: %{}
    end

    drop_if_exists index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:next_attempt_at, :source_system_id, :id],
                     name: "tickera_catalog_auto_apply_decisions_recovery_idx"
                   )

    create index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:next_attempt_at, :source_system_id, :id],
             name: "tickera_catalog_auto_apply_decisions_recovery_idx",
             where: "enqueue_state IN ('pending', 'claimed', 'retryable_failure')"
           )
  end
end
