defmodule EventSales.Repo.Migrations.Slice5WebhookIntakeSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:ingestion_webhook_events, [:delivery_id],
                     name: "ingestion_webhook_events_delivery_id_idx"
                   )
  end

  def down do
    create index(:ingestion_webhook_events, [:delivery_id],
             name: "ingestion_webhook_events_delivery_id_idx",
             unique: true
           )
  end
end
