defmodule EventSales.Repo.Migrations.Slice3Catalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_ticket_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :capacity, :bigint
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :uuid, null: false
    end

    create unique_index(:catalog_ticket_types, [:event_id, :name],
             name: "catalog_ticket_types_unique_name_per_event_index"
           )

    create table(:catalog_source_systems, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :kind, :text, null: false
      add :base_url, :text, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:catalog_source_systems, [:kind, :base_url],
             name: "catalog_source_systems_unique_kind_base_url_index"
           )

    create table(:catalog_product_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :woo_product_id, :bigint, null: false
      add :woo_variation_id, :bigint
      add :original_label, :text
      add :current_label, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "catalog_product_mappings_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id, :uuid, null: false
      add :ticket_type_id, :uuid, null: false
    end

    create index(
             :catalog_product_mappings,
             [:source_system_id, :woo_product_id, :woo_variation_id],
             name: "catalog_mappings_unique_active_variation_idx",
             unique: true,
             where: "active = TRUE AND woo_variation_id IS NOT NULL"
           )

    create index(:catalog_product_mappings, [:source_system_id, :woo_product_id],
             name: "catalog_mappings_unique_active_product_idx",
             unique: true,
             where: "active = TRUE AND woo_variation_id IS NULL"
           )

    create table(:catalog_product_mapping_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:catalog_product_mappings,
            column: :id,
            name: "catalog_product_mapping_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:catalog_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:catalog_ticket_types) do
      modify :event_id,
             references(:catalog_events,
               column: :id,
               name: "catalog_ticket_types_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end

    alter table(:catalog_product_mappings) do
      modify :event_id,
             references(:catalog_events,
               column: :id,
               name: "catalog_product_mappings_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )

      modify :ticket_type_id,
             references(:catalog_ticket_types,
               column: :id,
               name: "catalog_product_mappings_ticket_type_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict,
               on_update: :update_all
             )
    end

    alter table(:catalog_events) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :starts_at, :utc_datetime_usec
      add :ends_at, :utc_datetime_usec
      add :capacity, :bigint
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "catalog_events_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:catalog_events, [:source_system_id, :slug],
             name: "catalog_events_unique_slug_per_source_index"
           )

    create table(:catalog_event_dashboard_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :revenue_visible_to_event_owner, :boolean, null: false, default: false
      add :revenue_visible_to_event_staff, :boolean, null: false, default: false
      add :order_numbers_visible, :boolean, null: false, default: false
      add :pii_visible, :boolean, null: false, default: false
      add :access_expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "catalog_event_dashboard_settings_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:catalog_event_dashboard_settings, [:event_id],
             name: "catalog_event_dashboard_settings_unique_event_index"
           )
  end

  def down do
    drop constraint(
           :catalog_event_dashboard_settings,
           "catalog_event_dashboard_settings_event_id_fkey"
         )

    drop_if_exists unique_index(:catalog_event_dashboard_settings, [:event_id],
                     name: "catalog_event_dashboard_settings_unique_event_index"
                   )

    drop table(:catalog_event_dashboard_settings)

    drop constraint(:catalog_events, "catalog_events_source_system_id_fkey")

    drop_if_exists unique_index(:catalog_events, [:source_system_id, :slug],
                     name: "catalog_events_unique_slug_per_source_index"
                   )

    alter table(:catalog_events) do
      remove :source_system_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :capacity
      remove :ends_at
      remove :starts_at
      remove :slug
      remove :name
    end

    drop constraint(:catalog_product_mappings, "catalog_product_mappings_event_id_fkey")

    drop constraint(:catalog_product_mappings, "catalog_product_mappings_ticket_type_id_fkey")

    alter table(:catalog_product_mappings) do
      modify :ticket_type_id, :uuid
      modify :event_id, :uuid
    end

    drop constraint(:catalog_ticket_types, "catalog_ticket_types_event_id_fkey")

    alter table(:catalog_ticket_types) do
      modify :event_id, :uuid
    end

    drop table(:catalog_events)

    drop constraint(
           :catalog_product_mapping_versions,
           "catalog_product_mapping_versions_version_source_id_fkey"
         )

    drop table(:catalog_product_mapping_versions)

    drop constraint(:catalog_product_mappings, "catalog_product_mappings_source_system_id_fkey")

    drop_if_exists index(:catalog_product_mappings, [:source_system_id, :woo_product_id],
                     name: "catalog_mappings_unique_active_product_idx"
                   )

    drop_if_exists index(
                     :catalog_product_mappings,
                     [:source_system_id, :woo_product_id, :woo_variation_id],
                     name: "catalog_mappings_unique_active_variation_idx"
                   )

    drop table(:catalog_product_mappings)

    drop_if_exists unique_index(:catalog_source_systems, [:kind, :base_url],
                     name: "catalog_source_systems_unique_kind_base_url_index"
                   )

    drop table(:catalog_source_systems)

    drop_if_exists unique_index(:catalog_ticket_types, [:event_id, :name],
                     name: "catalog_ticket_types_unique_name_per_event_index"
                   )

    drop table(:catalog_ticket_types)
  end
end
