defmodule EventSales.Repo.Migrations.Slice5WebhookIntake do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_webhook_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :topic, :text, null: false
      add :resource_type, :text, null: false
      add :resource_id, :text, null: false
      add :delivery_id, :text, null: false
      add :payload, :map, null: false
      add :payload_hash, :text, null: false
      add :status, :text, null: false, default: "queued"
      add :received_at, :utc_datetime_usec, null: false
      add :signature_validated_at, :utc_datetime_usec, null: false
      add :raw_body_size, :bigint, null: false
      add :accepted_via, :text, null: false, default: "postgres"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_webhook_events_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:ingestion_webhook_events, [:received_at],
             name: "ingestion_webhook_events_received_at_idx"
           )

    create index(:ingestion_webhook_events, [:status],
             name: "ingestion_webhook_events_status_idx"
           )

    create unique_index(:ingestion_webhook_events, [:delivery_id],
             name: "ingestion_webhook_events_unique_delivery_id_index"
           )

    create table(:ingestion_webhook_delivery_failures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reason, :text, null: false
      add :topic, :text
      add :remote_ip_hash, :text
      add :user_agent_hash, :text
      add :metadata, :map, null: false, default: %{}
      add :received_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_webhook_delivery_failures_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:ingestion_webhook_delivery_failures, [:received_at],
             name: "ingestion_webhook_delivery_failures_received_at_idx"
           )

    create index(:ingestion_webhook_delivery_failures, [:reason],
             name: "ingestion_webhook_delivery_failures_reason_idx"
           )
  end

  def down do
    drop constraint(
           :ingestion_webhook_delivery_failures,
           "ingestion_webhook_delivery_failures_source_system_id_fkey"
         )

    drop_if_exists index(:ingestion_webhook_delivery_failures, [:reason],
                     name: "ingestion_webhook_delivery_failures_reason_idx"
                   )

    drop_if_exists index(:ingestion_webhook_delivery_failures, [:received_at],
                     name: "ingestion_webhook_delivery_failures_received_at_idx"
                   )

    drop table(:ingestion_webhook_delivery_failures)

    drop constraint(:ingestion_webhook_events, "ingestion_webhook_events_source_system_id_fkey")

    drop_if_exists unique_index(:ingestion_webhook_events, [:delivery_id],
                     name: "ingestion_webhook_events_unique_delivery_id_index"
                   )

    drop_if_exists index(:ingestion_webhook_events, [:status],
                     name: "ingestion_webhook_events_status_idx"
                   )

    drop_if_exists index(:ingestion_webhook_events, [:received_at],
                     name: "ingestion_webhook_events_received_at_idx"
                   )

    drop table(:ingestion_webhook_events)
  end
end
