defmodule EventSales.Repo.Migrations.Slice2AccountsIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:accounts_event_access_grants, [:user_id, :event_id, :role],
             name: "accounts_grants_unique_active_role_idx",
             unique: true,
             where: "active = TRUE"
           )

    create index(:accounts_event_access_grants, [:expires_at])

    create index(:accounts_event_access_grants, [:role])

    create index(:accounts_event_access_grants, [:event_id])

    create index(:accounts_event_access_grants, [:user_id])
  end

  def down do
    drop_if_exists index(:accounts_event_access_grants, [:user_id])

    drop_if_exists index(:accounts_event_access_grants, [:event_id])

    drop_if_exists index(:accounts_event_access_grants, [:role])

    drop_if_exists index(:accounts_event_access_grants, [:expires_at])

    drop_if_exists index(:accounts_event_access_grants, [:user_id, :event_id, :role],
                     name: "accounts_grants_unique_active_role_idx"
                   )
  end
end
