defmodule EventSales.Repo.Migrations.PreM5ReadyIx do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:ingestion_sync_runs, [:event_id, :coverage_certified_at, :finished_at, :id],
             name: "ingestion_sync_runs_historical_cert_lookup_idx",
             where: "sync_type = 'historical_backfill' AND coverage_certified_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(
                     :ingestion_sync_runs,
                     [:event_id, :coverage_certified_at, :finished_at, :id],
                     name: "ingestion_sync_runs_historical_cert_lookup_idx"
                   )
  end
end
