defmodule EventSales.Repo.Migrations.Slice2Accounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text
      add :active, :boolean, null: false, default: true
      add :hashed_password, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    create table(:accounts_user_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :role_id, :uuid, null: false
    end

    create unique_index(:accounts_user_roles, [:user_id, :role_id],
             name: "accounts_user_roles_unique_user_role_index"
           )

    create table(:accounts_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:accounts_user_roles) do
      modify :role_id,
             references(:accounts_roles,
               column: :id,
               name: "accounts_user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts_roles) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts_roles, [:name], name: "accounts_roles_unique_name_index")

    create table(:accounts_event_access_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_id, :uuid, null: false
      add :role, :text, null: false
      add :expires_at, :utc_datetime_usec
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_event_access_grants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:accounts_event_access_grants, "accounts_event_access_grants_user_id_fkey")

    drop table(:accounts_event_access_grants)

    drop_if_exists unique_index(:accounts_roles, [:name],
                     name: "accounts_roles_unique_name_index"
                   )

    alter table(:accounts_roles) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:accounts_user_roles, "accounts_user_roles_role_id_fkey")

    alter table(:accounts_user_roles) do
      modify :role_id, :uuid
    end

    drop table(:accounts_roles)

    drop constraint(:accounts_user_roles, "accounts_user_roles_user_id_fkey")

    drop_if_exists unique_index(:accounts_user_roles, [:user_id, :role_id],
                     name: "accounts_user_roles_unique_user_role_index"
                   )

    drop table(:accounts_user_roles)

    drop_if_exists unique_index(:accounts_users, [:email],
                     name: "accounts_users_unique_email_index"
                   )

    drop table(:accounts_users)
  end
end
