defmodule EventSales.Repo.Migrations.Slice1450dTickeraReconciliation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_tickera_reconciliation_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_via, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "queued"
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :last_error, :text
      add :woo_orders_scanned_count, :bigint, null: false, default: 0
      add :woo_items_scanned_count, :bigint, null: false, default: 0
      add :tickera_snapshots_scanned_count, :bigint, null: false, default: 0
      add :findings_created_count, :bigint, null: false, default: 0
      add :findings_open_count, :bigint, null: false, default: 0
      add :findings_resolved_count, :bigint, null: false, default: 0
      add :critical_count, :bigint, null: false, default: 0
      add :warning_count, :bigint, null: false, default: 0
      add :info_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tickera_event_source_id,
          references(:ingestion_tickera_event_sources,
            column: :id,
            name: "ingestion_tickera_reconciliation_runs_tickera_event_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_reconciliation_runs_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_tickera_reconciliation_runs_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :tickera_attendee_sync_run_id,
          references(:ingestion_tickera_attendee_sync_runs,
            column: :id,
            name: "ingestion_tickera_reconciliation_runs_tickera_attendee_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:ingestion_tickera_reconciliation_runs, [:tickera_event_source_id, :status],
             name: "ingestion_tickera_reconciliation_runs_source_status_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:event_id, :status],
             name: "ingestion_tickera_reconciliation_runs_event_status_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:inserted_at],
             name: "ingestion_tickera_reconciliation_runs_inserted_at_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:status],
             name: "ingestion_tickera_reconciliation_runs_status_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:event_id],
             name: "ingestion_tickera_reconciliation_runs_event_id_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:source_system_id],
             name: "ingestion_tickera_reconciliation_runs_source_system_idx"
           )

    create index(:ingestion_tickera_reconciliation_runs, [:tickera_event_source_id],
             name: "ingestion_tickera_reconciliation_runs_source_idx"
           )

    create table(:ingestion_tickera_reconciliation_findings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_scope_key, :text, null: false
      add :finding_type, :text, null: false
      add :severity, :text, null: false
      add :status, :text, null: false, default: "open"
      add :ticket_code, :text
      add :checksum, :text
      add :woo_order_status, :text
      add :tickera_payment_status, :text
      add :woo_quantity, :bigint
      add :tickera_quantity, :bigint
      add :details, :map, null: false, default: %{}
      add :fingerprint, :text, null: false
      add :first_seen_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec, null: false
      add :resolved_at, :utc_datetime_usec
      add :resolution_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tickera_reconciliation_run_id,
          references(:ingestion_tickera_reconciliation_runs,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_tickera_reconciliation_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :tickera_event_source_id,
          references(:ingestion_tickera_event_sources,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_tickera_event_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :order_id,
          references(:sales_orders,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :order_item_id,
          references(:sales_order_items,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_order_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :tickera_attendee_snapshot_id,
          references(:ingestion_tickera_attendee_snapshots,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_tickera_attendee_snapshot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :ticket_type_id,
          references(:catalog_ticket_types,
            column: :id,
            name: "ingestion_tickera_reconciliation_findings_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(
             :ingestion_tickera_reconciliation_findings,
             [:tickera_reconciliation_run_id, :finding_type],
             name: "ingestion_tickera_reconciliation_findings_run_type_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:event_id, :severity],
             name: "ingestion_tickera_reconciliation_findings_event_severity_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:event_id, :status],
             name: "ingestion_tickera_reconciliation_findings_event_status_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:inserted_at],
             name: "ingestion_tickera_reconciliation_findings_inserted_at_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:finding_type],
             name: "ingestion_tickera_reconciliation_findings_type_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:severity],
             name: "ingestion_tickera_reconciliation_findings_severity_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:status],
             name: "ingestion_tickera_reconciliation_findings_status_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:source_scope_key],
             name: "ingestion_tickera_reconciliation_findings_scope_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:tickera_event_source_id],
             name: "ingestion_tickera_reconciliation_findings_source_idx"
           )

    create index(:ingestion_tickera_reconciliation_findings, [:event_id],
             name: "ingestion_tickera_reconciliation_findings_event_id_idx"
           )

    create unique_index(
             :ingestion_tickera_reconciliation_findings,
             [:event_id, :source_scope_key, :fingerprint],
             name: "tickera_recon_findings_source_fingerprint_idx"
           )
  end

  def down do
    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_tickera_reconciliation_run_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_tickera_event_source_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_event_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_order_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_order_item_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_tickera_attendee_snapshot_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_findings,
           "ingestion_tickera_reconciliation_findings_ticket_type_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_tickera_reconciliation_findings,
                     [:event_id, :source_scope_key, :fingerprint],
                     name: "tickera_recon_findings_source_fingerprint_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:event_id],
                     name: "ingestion_tickera_reconciliation_findings_event_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:tickera_event_source_id],
                     name: "ingestion_tickera_reconciliation_findings_source_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:source_scope_key],
                     name: "ingestion_tickera_reconciliation_findings_scope_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:status],
                     name: "ingestion_tickera_reconciliation_findings_status_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:severity],
                     name: "ingestion_tickera_reconciliation_findings_severity_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:finding_type],
                     name: "ingestion_tickera_reconciliation_findings_type_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:inserted_at],
                     name: "ingestion_tickera_reconciliation_findings_inserted_at_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:event_id, :status],
                     name: "ingestion_tickera_reconciliation_findings_event_status_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_findings, [:event_id, :severity],
                     name: "ingestion_tickera_reconciliation_findings_event_severity_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_reconciliation_findings,
                     [:tickera_reconciliation_run_id, :finding_type],
                     name: "ingestion_tickera_reconciliation_findings_run_type_idx"
                   )

    drop table(:ingestion_tickera_reconciliation_findings)

    drop constraint(
           :ingestion_tickera_reconciliation_runs,
           "ingestion_tickera_reconciliation_runs_tickera_event_source_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_runs,
           "ingestion_tickera_reconciliation_runs_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_runs,
           "ingestion_tickera_reconciliation_runs_event_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_reconciliation_runs,
           "ingestion_tickera_reconciliation_runs_tickera_attendee_sync_run_id_fkey"
         )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:tickera_event_source_id],
                     name: "ingestion_tickera_reconciliation_runs_source_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:source_system_id],
                     name: "ingestion_tickera_reconciliation_runs_source_system_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:event_id],
                     name: "ingestion_tickera_reconciliation_runs_event_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:status],
                     name: "ingestion_tickera_reconciliation_runs_status_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:inserted_at],
                     name: "ingestion_tickera_reconciliation_runs_inserted_at_idx"
                   )

    drop_if_exists index(:ingestion_tickera_reconciliation_runs, [:event_id, :status],
                     name: "ingestion_tickera_reconciliation_runs_event_status_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_reconciliation_runs,
                     [:tickera_event_source_id, :status],
                     name: "ingestion_tickera_reconciliation_runs_source_status_idx"
                   )

    drop table(:ingestion_tickera_reconciliation_runs)
  end
end
