defmodule EventSales.Repo.Migrations.M503bEventDimensionRefundPrimitives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:analytics_event_dimension_aggregate_snapshots) do
      add :refund_ticket_quantity, :bigint, null: false, default: 0
      add :refund_ticket_value, :decimal, null: false, default: "0"
    end

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_refund_ticket_quantity_check,
             check: """
               refund_ticket_quantity >= 0
             """
           )

    create constraint(
             :analytics_event_dimension_aggregate_snapshots,
             :analytics_event_dim_agg_snapshots_refund_ticket_value_check,
             check: """
               refund_ticket_value >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_refund_ticket_value_check
                   )

    drop_if_exists constraint(
                     :analytics_event_dimension_aggregate_snapshots,
                     :analytics_event_dim_agg_snapshots_refund_ticket_quantity_check
                   )

    alter table(:analytics_event_dimension_aggregate_snapshots) do
      remove :refund_ticket_value
      remove :refund_ticket_quantity
    end
  end
end
