defmodule EventSales.Repo.Migrations.M405MismatchCategoryNotNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_mismatch_category_check
                   )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_mismatch_category_check,
             check: """
               (
               ("matched?" = true AND mismatch_category IS NULL)
               OR
               ("matched?" = false AND mismatch_category IS NOT NULL AND mismatch_category = CASE primitive
                 WHEN 'gross_ticket_quantity' THEN 'gross_quantity_mismatch'
                 WHEN 'gross_ticket_value' THEN 'gross_value_mismatch'
                 WHEN 'refund_ticket_quantity' THEN 'refund_quantity_mismatch'
                 WHEN 'refund_ticket_value' THEN 'refund_value_mismatch'
                 WHEN 'net_ticket_quantity' THEN 'net_quantity_mismatch'
                 WHEN 'net_ticket_value' THEN 'net_value_mismatch'
               END)
             )

             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_mismatch_category_check
                   )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_mismatch_category_check,
             check: """
               (
               ("matched?" = true AND mismatch_category IS NULL)
               OR
               ("matched?" = false AND mismatch_category = CASE primitive
                 WHEN 'gross_ticket_quantity' THEN 'gross_quantity_mismatch'
                 WHEN 'gross_ticket_value' THEN 'gross_value_mismatch'
                 WHEN 'refund_ticket_quantity' THEN 'refund_quantity_mismatch'
                 WHEN 'refund_ticket_value' THEN 'refund_value_mismatch'
                 WHEN 'net_ticket_quantity' THEN 'net_quantity_mismatch'
                 WHEN 'net_ticket_value' THEN 'net_value_mismatch'
               END)
             )

             """
           )
  end
end
