defmodule EventSales.Repo.Migrations.PreM5TimeDEventSourceFreshnessSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:analytics_event_source_freshness_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :order_source_watermark_at, :utc_datetime_usec
      add :refund_source_watermark_at, :utc_datetime_usec
      add :sync_source_observed_at, :utc_datetime_usec
      add :projection_version, :bigint, null: false, default: 1
      add :projection_refreshed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_event_source_freshness_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:analytics_event_source_freshness_snapshots, [:event_id],
             name: "analytics_event_source_freshness_snapshots_event_id_idx"
           )
  end

  def down do
    drop constraint(
           :analytics_event_source_freshness_snapshots,
           "analytics_event_source_freshness_snapshots_event_id_fkey"
         )

    drop_if_exists unique_index(:analytics_event_source_freshness_snapshots, [:event_id],
                     name: "analytics_event_source_freshness_snapshots_event_id_idx"
                   )

    drop table(:analytics_event_source_freshness_snapshots)
  end
end
