defmodule EventSales.Repo.Migrations.Vs26e2CatalogAutoApplyDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_tickera_catalog_auto_apply_decisions) do
      modify :historical_summary, :map,
        default: %{
          "affected_pending_lines" => 0,
          "affected_quantity" => 0,
          "eligible_lines" => 0,
          "deferred_lines" => 0,
          "conflicting_lines" => 0,
          "already_mapped_lines" => 0,
          "warning_count" => 0,
          "unresolved_destination_count" => 0,
          "unknown_classification_count" => 0
        }
    end
  end

  def down do
    raise """
    VS-26E.2 rollback is intentionally audit-preserving and irreversible.
    Roll application code back with the hard kill disabled while retaining
    additive configuration, decision, linkage, origin, and audit schema.
    """
  end
end
