defmodule EventSales.Repo.Migrations.M405AuditCheckConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(
             :ingestion_financial_reconciliation_runs,
             :ingestion_fin_recon_runs_requested_via_check,
             check: """
               requested_via IN ('manual', 'system')
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_runs,
             :ingestion_fin_recon_runs_status_check,
             check: """
               status IN ('queued', 'running', 'passed', 'mismatched', 'superseded', 'failed', 'cancelled')
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_findings,
             :ingestion_fin_recon_findings_category_check,
             check: """
               category IN ('source_snapshot_stale', 'refund_identity_drift', 'http_under_lock', 'historical_recognition_unproven', 'timestamp_incomplete', 'currency_conflict', 'unresolved_attribution', 'financial_primitive_incomplete', 'missing_source_fact', 'missing_refund_detail', 'missing_local_fact', 'invalid_scope', 'comparison_scope_mismatch', 'invalid_comparison_input')
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_findings,
             :ingestion_fin_recon_findings_origin_check,
             check: """
               origin IN ('source', 'local', 'comparator')
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_findings,
             :ingestion_fin_recon_findings_fingerprint_check,
             check: """
               fingerprint ~ '^[0-9a-f]{64}$'
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_currency_check,
             check: """
               btrim(currency) <> ''
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_primitive_check,
             check: """
               primitive IN ('gross_ticket_quantity', 'gross_ticket_value', 'refund_ticket_quantity', 'refund_ticket_value', 'net_ticket_quantity', 'net_ticket_value')
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_delta_check,
             check: """
               delta = local_value - source_value
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_matched_check,
             check: """
               "matched?" = (source_value = local_value)
             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_mismatch_category_check,
             check: """
               (
               ("matched?" = true AND mismatch_category IS NULL)
               OR
               ("matched?" = false AND mismatch_category = CASE primitive
                 WHEN 'gross_ticket_quantity' THEN 'gross_quantity_mismatch'
                 WHEN 'gross_ticket_value' THEN 'gross_value_mismatch'
                 WHEN 'refund_ticket_quantity' THEN 'refund_quantity_mismatch'
                 WHEN 'refund_ticket_value' THEN 'refund_value_mismatch'
                 WHEN 'net_ticket_quantity' THEN 'net_quantity_mismatch'
                 WHEN 'net_ticket_value' THEN 'net_value_mismatch'
               END)
             )

             """
           )

    create constraint(
             :ingestion_financial_reconciliation_metrics,
             :ingestion_fin_recon_metrics_quantity_integral_check,
             check: """
               (
               primitive NOT IN ('gross_ticket_quantity', 'refund_ticket_quantity', 'net_ticket_quantity')
               OR (
                 source_value = trunc(source_value)
                 AND local_value = trunc(local_value)
                 AND delta = trunc(delta)
               )
             )

             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_quantity_integral_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_mismatch_category_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_matched_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_delta_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_primitive_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_metrics,
                     :ingestion_fin_recon_metrics_currency_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_findings,
                     :ingestion_fin_recon_findings_fingerprint_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_findings,
                     :ingestion_fin_recon_findings_origin_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_findings,
                     :ingestion_fin_recon_findings_category_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_runs,
                     :ingestion_fin_recon_runs_status_check
                   )

    drop_if_exists constraint(
                     :ingestion_financial_reconciliation_runs,
                     :ingestion_fin_recon_runs_requested_via_check
                   )
  end
end
