defmodule EventSales.Repo.Migrations.M207EventAnalyticsOnboardingState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_events) do
      add :analytics_onboarding_state, :text, null: false, default: "unverified"
    end
  end

  def down do
    alter table(:catalog_events) do
      remove :analytics_onboarding_state
    end
  end
end
