defmodule EventSales.Repo.Migrations.M30102aHistoricalRunContract do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_sync_runs) do
      add :sync_type, :text, null: false, default: "reconciliation"
    end

    create index(:ingestion_sync_runs, [:source_system_id, :event_id],
             name: "ingestion_sync_runs_active_historical_event_idx",
             unique: true,
             where:
               "sync_type = 'historical_backfill' AND status IN ('queued', 'running', 'paused')"
           )
  end

  def down do
    drop_if_exists index(:ingestion_sync_runs, [:source_system_id, :event_id],
                     name: "ingestion_sync_runs_active_historical_event_idx"
                   )

    alter table(:ingestion_sync_runs) do
      remove :sync_type
    end
  end
end
