defmodule EventSales.Repo.Migrations.M405DurableFinancialReconciliation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_financial_reconciliation_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_via, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "queued"
      add :coverage_start, :utc_datetime_usec, null: false
      add :sales_covered_through, :utc_datetime_usec, null: false
      add :refunds_covered_through, :utc_datetime_usec, null: false
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :historical_sync_run_id,
          references(:ingestion_sync_runs,
            column: :id,
            name: "ingestion_financial_reconciliation_runs_historical_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_financial_reconciliation_runs_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_financial_reconciliation_runs_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:ingestion_financial_reconciliation_runs, [:event_id],
             name: "ingestion_fin_recon_runs_event_id_idx"
           )

    create index(:ingestion_financial_reconciliation_runs, [:historical_sync_run_id],
             name: "ingestion_fin_recon_runs_sync_run_id_idx"
           )

    create index(:ingestion_financial_reconciliation_runs, [:status],
             name: "ingestion_fin_recon_runs_status_idx"
           )

    create index(:ingestion_financial_reconciliation_runs, [:finished_at],
             name: "ingestion_fin_recon_runs_finished_at_idx"
           )

    create index(
             :ingestion_financial_reconciliation_runs,
             [:event_id, :historical_sync_run_id, :finished_at],
             name: "ingestion_fin_recon_runs_cert_lookup_idx"
           )

    create index(:ingestion_financial_reconciliation_runs, [:event_id, :historical_sync_run_id],
             name: "ingestion_fin_recon_runs_active_idx",
             unique: true,
             where: "status IN ('queued', 'running')"
           )

    create table(:ingestion_financial_reconciliation_findings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :category, :text, null: false
      add :origin, :text, null: false
      add :details, :map, null: false, default: %{}
      add :fingerprint, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :financial_reconciliation_run_id,
          references(:ingestion_financial_reconciliation_runs,
            column: :id,
            name:
              "ingestion_financial_reconciliation_findings_financial_reconciliation_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(
             :ingestion_financial_reconciliation_findings,
             [:financial_reconciliation_run_id, :fingerprint],
             name: "ingestion_fin_recon_findings_identity_idx"
           )

    create index(:ingestion_financial_reconciliation_findings, [:financial_reconciliation_run_id],
             name: "ingestion_fin_recon_findings_run_id_idx"
           )

    create index(:ingestion_financial_reconciliation_findings, [:category],
             name: "ingestion_fin_recon_findings_category_idx"
           )

    create index(:ingestion_financial_reconciliation_findings, [:origin],
             name: "ingestion_fin_recon_findings_origin_idx"
           )

    create table(:ingestion_financial_reconciliation_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false
      add :primitive, :text, null: false
      add :source_value, :decimal, null: false
      add :local_value, :decimal, null: false
      add :delta, :decimal, null: false
      add :matched?, :boolean, null: false
      add :mismatch_category, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :financial_reconciliation_run_id,
          references(:ingestion_financial_reconciliation_runs,
            column: :id,
            name:
              "ingestion_financial_reconciliation_metrics_financial_reconciliation_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(
             :ingestion_financial_reconciliation_metrics,
             [:financial_reconciliation_run_id, :currency, :primitive],
             name: "ingestion_fin_recon_metrics_identity_idx"
           )

    create index(:ingestion_financial_reconciliation_metrics, [:financial_reconciliation_run_id],
             name: "ingestion_fin_recon_metrics_run_id_idx"
           )
  end

  def down do
    drop_if_exists index(
                     :ingestion_financial_reconciliation_metrics,
                     [:financial_reconciliation_run_id],
                     name: "ingestion_fin_recon_metrics_run_id_idx"
                   )

    drop constraint(
           :ingestion_financial_reconciliation_metrics,
           "ingestion_financial_reconciliation_metrics_financial_reconciliation_run_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_financial_reconciliation_metrics,
                     [:financial_reconciliation_run_id, :currency, :primitive],
                     name: "ingestion_fin_recon_metrics_identity_idx"
                   )

    drop table(:ingestion_financial_reconciliation_metrics)

    drop_if_exists index(:ingestion_financial_reconciliation_findings, [:origin],
                     name: "ingestion_fin_recon_findings_origin_idx"
                   )

    drop_if_exists index(:ingestion_financial_reconciliation_findings, [:category],
                     name: "ingestion_fin_recon_findings_category_idx"
                   )

    drop_if_exists index(
                     :ingestion_financial_reconciliation_findings,
                     [:financial_reconciliation_run_id],
                     name: "ingestion_fin_recon_findings_run_id_idx"
                   )

    drop constraint(
           :ingestion_financial_reconciliation_findings,
           "ingestion_financial_reconciliation_findings_financial_reconciliation_run_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_financial_reconciliation_findings,
                     [:financial_reconciliation_run_id, :fingerprint],
                     name: "ingestion_fin_recon_findings_identity_idx"
                   )

    drop table(:ingestion_financial_reconciliation_findings)

    drop_if_exists index(
                     :ingestion_financial_reconciliation_runs,
                     [:event_id, :historical_sync_run_id],
                     name: "ingestion_fin_recon_runs_active_idx"
                   )

    drop_if_exists index(
                     :ingestion_financial_reconciliation_runs,
                     [:event_id, :historical_sync_run_id, :finished_at],
                     name: "ingestion_fin_recon_runs_cert_lookup_idx"
                   )

    drop_if_exists index(:ingestion_financial_reconciliation_runs, [:finished_at],
                     name: "ingestion_fin_recon_runs_finished_at_idx"
                   )

    drop_if_exists index(:ingestion_financial_reconciliation_runs, [:status],
                     name: "ingestion_fin_recon_runs_status_idx"
                   )

    drop_if_exists index(:ingestion_financial_reconciliation_runs, [:historical_sync_run_id],
                     name: "ingestion_fin_recon_runs_sync_run_id_idx"
                   )

    drop_if_exists index(:ingestion_financial_reconciliation_runs, [:event_id],
                     name: "ingestion_fin_recon_runs_event_id_idx"
                   )

    drop constraint(
           :ingestion_financial_reconciliation_runs,
           "ingestion_financial_reconciliation_runs_event_id_fkey"
         )

    drop constraint(
           :ingestion_financial_reconciliation_runs,
           "ingestion_financial_reconciliation_runs_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_financial_reconciliation_runs,
           "ingestion_financial_reconciliation_runs_historical_sync_run_id_fkey"
         )

    drop table(:ingestion_financial_reconciliation_runs)
  end
end
