defmodule EventSales.Repo.Migrations.Slice97HistoricalReportingSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:analytics_event_aggregate_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :total_sold, :bigint, null: false, default: 0
      add :total_revenue, :decimal, null: false, default: "0"
      add :today_sold, :bigint, null: false, default: 0
      add :today_revenue, :decimal, null: false, default: "0"
      add :status_breakdown, :map, null: false, default: %{}
      add :currency, :text, null: false
      add :business_timezone, :text, null: false
      add :refreshed_at, :utc_datetime_usec, null: false
      add :source_watermark_at, :utc_datetime_usec
      add :source_row_count, :bigint, null: false, default: 0
      add :snapshot_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_event_aggregate_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:analytics_event_aggregate_snapshots, [:source_watermark_at],
             name: "analytics_event_aggregate_snapshots_source_watermark_at_idx"
           )

    create index(:analytics_event_aggregate_snapshots, [:refreshed_at],
             name: "analytics_event_aggregate_snapshots_refreshed_at_idx"
           )

    create unique_index(:analytics_event_aggregate_snapshots, [:event_id],
             name: "analytics_event_aggregate_snapshots_unique_event_index"
           )

    create table(:analytics_daily_sales_aggregate_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :business_date, :date, null: false
      add :total_sold, :bigint, null: false, default: 0
      add :total_revenue, :decimal, null: false, default: "0"
      add :today_sold, :bigint, null: false, default: 0
      add :today_revenue, :decimal, null: false, default: "0"
      add :status_breakdown, :map, null: false, default: %{}
      add :currency, :text, null: false
      add :business_timezone, :text, null: false
      add :refreshed_at, :utc_datetime_usec, null: false
      add :source_watermark_at, :utc_datetime_usec
      add :source_row_count, :bigint, null: false, default: 0
      add :snapshot_version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "analytics_daily_sales_aggregate_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:analytics_daily_sales_aggregate_snapshots, [:refreshed_at],
             name: "analytics_daily_sales_aggregate_snapshots_refreshed_at_idx"
           )

    create index(:analytics_daily_sales_aggregate_snapshots, [:business_date],
             name: "analytics_daily_sales_aggregate_snapshots_business_date_idx"
           )

    create index(:analytics_daily_sales_aggregate_snapshots, [:event_id],
             name: "analytics_daily_sales_aggregate_snapshots_event_id_idx"
           )

    create unique_index(
             :analytics_daily_sales_aggregate_snapshots,
             [:event_id, :business_date, :business_timezone],
             name: "analytics_daily_snapshots_unique_scope_idx"
           )
  end

  def down do
    drop constraint(
           :analytics_daily_sales_aggregate_snapshots,
           "analytics_daily_sales_aggregate_snapshots_event_id_fkey"
         )

    drop_if_exists unique_index(
                     :analytics_daily_sales_aggregate_snapshots,
                     [:event_id, :business_date, :business_timezone],
                     name: "analytics_daily_snapshots_unique_scope_idx"
                   )

    drop_if_exists index(:analytics_daily_sales_aggregate_snapshots, [:event_id],
                     name: "analytics_daily_sales_aggregate_snapshots_event_id_idx"
                   )

    drop_if_exists index(:analytics_daily_sales_aggregate_snapshots, [:business_date],
                     name: "analytics_daily_sales_aggregate_snapshots_business_date_idx"
                   )

    drop_if_exists index(:analytics_daily_sales_aggregate_snapshots, [:refreshed_at],
                     name: "analytics_daily_sales_aggregate_snapshots_refreshed_at_idx"
                   )

    drop table(:analytics_daily_sales_aggregate_snapshots)

    drop constraint(
           :analytics_event_aggregate_snapshots,
           "analytics_event_aggregate_snapshots_event_id_fkey"
         )

    drop_if_exists unique_index(:analytics_event_aggregate_snapshots, [:event_id],
                     name: "analytics_event_aggregate_snapshots_unique_event_index"
                   )

    drop_if_exists index(:analytics_event_aggregate_snapshots, [:refreshed_at],
                     name: "analytics_event_aggregate_snapshots_refreshed_at_idx"
                   )

    drop_if_exists index(:analytics_event_aggregate_snapshots, [:source_watermark_at],
                     name: "analytics_event_aggregate_snapshots_source_watermark_at_idx"
                   )

    drop table(:analytics_event_aggregate_snapshots)
  end
end
