defmodule EventSales.Repo.Migrations.AshBaselineAuthUserProof do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_baseline_auth_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:ash_baseline_auth_users, [:email],
             name: "ash_baseline_auth_users_unique_email_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ash_baseline_auth_users, [:email],
                     name: "ash_baseline_auth_users_unique_email_index"
                   )

    drop table(:ash_baseline_auth_users)
  end
end
