defmodule EventSales.Repo.Migrations.Slice4Sales do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sales_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :woo_order_id, :bigint, null: false
      add :order_number, :text
      add :status, :text, null: false, default: "pending"
      add :currency, :text, null: false
      add :completed_at, :utc_datetime_usec
      add :created_at_source, :utc_datetime_usec, null: false
      add :updated_at_source, :utc_datetime_usec, null: false
      add :customer_name, :text
      add :customer_email, :text
      add :raw_total, :decimal, null: false
      add :raw_discount_total, :decimal, null: false, default: "0"
      add :raw_tax_total, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "sales_orders_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:sales_orders, [:order_number], name: "sales_orders_order_number_idx")

    create index(:sales_orders, [:updated_at_source], name: "sales_orders_updated_at_source_idx")

    create index(:sales_orders, [:completed_at], name: "sales_orders_completed_at_idx")

    create index(:sales_orders, [:status], name: "sales_orders_status_idx")

    create index(:sales_orders, [:source_system_id], name: "sales_orders_source_system_id_idx")

    create unique_index(:sales_orders, [:source_system_id, :woo_order_id],
             name: "sales_orders_unique_source_order_index"
           )

    create table(:sales_order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :woo_line_item_id, :bigint, null: false
      add :woo_product_id, :bigint, null: false
      add :woo_variation_id, :bigint
      add :name, :text
      add :quantity, :bigint, null: false
      add :line_subtotal, :decimal, null: false
      add :line_total, :decimal, null: false
      add :discount_total, :decimal, null: false, default: "0"
      add :item_kind, :text, null: false, default: "unknown"
      add :mapping_status, :text, null: false, default: "pending_mapping_resolution"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:sales_orders,
            column: :id,
            name: "sales_order_items_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "sales_order_items_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )

      add :ticket_type_id,
          references(:catalog_ticket_types,
            column: :id,
            name: "sales_order_items_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )
    end

    create index(:sales_order_items, [:event_id, :mapping_status],
             name: "sales_order_items_event_mapping_status_idx"
           )

    create index(:sales_order_items, [:woo_product_id, :woo_variation_id],
             name: "sales_order_items_woo_product_variation_idx"
           )

    create index(:sales_order_items, [:mapping_status],
             name: "sales_order_items_mapping_status_idx"
           )

    create index(:sales_order_items, [:ticket_type_id],
             name: "sales_order_items_ticket_type_id_idx"
           )

    create index(:sales_order_items, [:event_id], name: "sales_order_items_event_id_idx")

    create index(:sales_order_items, [:order_id], name: "sales_order_items_order_id_idx")

    create unique_index(:sales_order_items, [:order_id, :woo_line_item_id],
             name: "sales_order_items_unique_order_line_index"
           )

    create table(:sales_coupon_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :discount_amount, :decimal, null: false
      add :discount_tax, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:sales_orders,
            column: :id,
            name: "sales_coupon_snapshots_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:sales_coupon_snapshots, [:order_id],
             name: "sales_coupon_snapshots_order_id_idx"
           )

    create unique_index(:sales_coupon_snapshots, [:order_id, :code],
             name: "sales_coupon_snapshots_unique_order_code_index"
           )
  end

  def down do
    drop constraint(:sales_coupon_snapshots, "sales_coupon_snapshots_order_id_fkey")

    drop_if_exists unique_index(:sales_coupon_snapshots, [:order_id, :code],
                     name: "sales_coupon_snapshots_unique_order_code_index"
                   )

    drop_if_exists index(:sales_coupon_snapshots, [:order_id],
                     name: "sales_coupon_snapshots_order_id_idx"
                   )

    drop table(:sales_coupon_snapshots)

    drop constraint(:sales_order_items, "sales_order_items_order_id_fkey")

    drop constraint(:sales_order_items, "sales_order_items_event_id_fkey")

    drop constraint(:sales_order_items, "sales_order_items_ticket_type_id_fkey")

    drop_if_exists unique_index(:sales_order_items, [:order_id, :woo_line_item_id],
                     name: "sales_order_items_unique_order_line_index"
                   )

    drop_if_exists index(:sales_order_items, [:order_id], name: "sales_order_items_order_id_idx")

    drop_if_exists index(:sales_order_items, [:event_id], name: "sales_order_items_event_id_idx")

    drop_if_exists index(:sales_order_items, [:ticket_type_id],
                     name: "sales_order_items_ticket_type_id_idx"
                   )

    drop_if_exists index(:sales_order_items, [:mapping_status],
                     name: "sales_order_items_mapping_status_idx"
                   )

    drop_if_exists index(:sales_order_items, [:woo_product_id, :woo_variation_id],
                     name: "sales_order_items_woo_product_variation_idx"
                   )

    drop_if_exists index(:sales_order_items, [:event_id, :mapping_status],
                     name: "sales_order_items_event_mapping_status_idx"
                   )

    drop table(:sales_order_items)

    drop constraint(:sales_orders, "sales_orders_source_system_id_fkey")

    drop_if_exists unique_index(:sales_orders, [:source_system_id, :woo_order_id],
                     name: "sales_orders_unique_source_order_index"
                   )

    drop_if_exists index(:sales_orders, [:source_system_id],
                     name: "sales_orders_source_system_id_idx"
                   )

    drop_if_exists index(:sales_orders, [:status], name: "sales_orders_status_idx")

    drop_if_exists index(:sales_orders, [:completed_at], name: "sales_orders_completed_at_idx")

    drop_if_exists index(:sales_orders, [:updated_at_source],
                     name: "sales_orders_updated_at_source_idx"
                   )

    drop_if_exists index(:sales_orders, [:order_number], name: "sales_orders_order_number_idx")

    drop table(:sales_orders)
  end
end
