defmodule EventSales.Repo.Migrations.Slice7OrderPaymentMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_orders) do
      add :payment_method, :text
      add :payment_method_title, :text
      add :payment_gateway_transaction_id, :text
    end
  end

  def down do
    alter table(:sales_orders) do
      remove :payment_gateway_transaction_id
      remove :payment_method_title
      remove :payment_method
    end
  end
end
