defmodule EventSales.Repo.Migrations.Slice14ReconciliationSyncRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:ingestion_sync_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_via, :text, null: false
      add :sync_mode, :text, null: false
      add :status, :text, null: false, default: "queued"
      add :pause_reason, :text
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :paused_until, :utc_datetime_usec
      add :date_from, :utc_datetime_usec
      add :date_to, :utc_datetime_usec
      add :last_error, :text
      add :orders_seen_count, :bigint, null: false, default: 0
      add :orders_matched_count, :bigint, null: false, default: 0
      add :orders_upserted_count, :bigint, null: false, default: 0
      add :orders_stale_count, :bigint, null: false, default: 0
      add :orders_failed_count, :bigint, null: false, default: 0
      add :errors_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_sync_runs_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_sync_runs_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create_if_not_exists index(:ingestion_sync_runs, [:requested_via],
                           name: "ingestion_sync_runs_requested_via_idx"
                         )

    create_if_not_exists index(:ingestion_sync_runs, [:sync_mode],
                           name: "ingestion_sync_runs_sync_mode_idx"
                         )

    create_if_not_exists index(:ingestion_sync_runs, [:started_at],
                           name: "ingestion_sync_runs_started_at_idx"
                         )

    create_if_not_exists index(:ingestion_sync_runs, [:status],
                           name: "ingestion_sync_runs_status_idx"
                         )

    create_if_not_exists index(:ingestion_sync_runs, [:event_id],
                           name: "ingestion_sync_runs_event_id_idx"
                         )

    create_if_not_exists index(:ingestion_sync_runs, [:source_system_id],
                           name: "ingestion_sync_runs_source_system_id_idx"
                         )
  end

  def down do
    drop constraint(:ingestion_sync_runs, "ingestion_sync_runs_source_system_id_fkey")

    drop constraint(:ingestion_sync_runs, "ingestion_sync_runs_event_id_fkey")

    drop_if_exists index(:ingestion_sync_runs, [:source_system_id],
                     name: "ingestion_sync_runs_source_system_id_idx"
                   )

    drop_if_exists index(:ingestion_sync_runs, [:event_id],
                     name: "ingestion_sync_runs_event_id_idx"
                   )

    drop_if_exists index(:ingestion_sync_runs, [:status], name: "ingestion_sync_runs_status_idx")

    drop_if_exists index(:ingestion_sync_runs, [:started_at],
                     name: "ingestion_sync_runs_started_at_idx"
                   )

    drop_if_exists index(:ingestion_sync_runs, [:sync_mode],
                     name: "ingestion_sync_runs_sync_mode_idx"
                   )

    drop_if_exists index(:ingestion_sync_runs, [:requested_via],
                     name: "ingestion_sync_runs_requested_via_idx"
                   )

    drop table(:ingestion_sync_runs)
  end
end
