defmodule EventSales.Repo.Migrations.Vs26e1CatalogChangeTrigger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_catalog_change_pending_targets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :target_type, :text, null: false
      add :target_id, :bigint, null: false
      add :state, :text, null: false, default: "pending"
      add :generation, :bigint, null: false, default: 1
      add :dispatched_generation, :bigint, null: false, default: 0
      add :latest_source_updated_at, :utc_datetime_usec, null: false
      add :latest_reason, :text, null: false
      add :first_received_at, :utc_datetime_usec, null: false
      add :last_received_at, :utc_datetime_usec, null: false
      add :quiet_until, :utc_datetime_usec, null: false
      add :recheck_at, :utc_datetime_usec
      add :dispatch_attempts, :bigint, null: false, default: 0
      add :last_error, :string, size: 120

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_catalog_change_pending_targets_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :catalog_sync_run_id,
          references(:ingestion_tickera_catalog_sync_runs,
            column: :id,
            name: "ingestion_catalog_change_pending_targets_catalog_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          )
    end

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_target_type,
             check: "target_type IN ('event', 'product', 'variation')"
           )

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_target_id,
             check: "target_id > 0"
           )

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_target_state,
             check:
               "state IN ('pending', 'deferred', 'queued', 'preview_ready', 'settled', 'failed')"
           )

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_generations,
             check:
               "generation >= 1 AND dispatched_generation >= 0 AND dispatched_generation <= generation"
           )

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_attempts,
             check: "dispatch_attempts BETWEEN 0 AND 100"
           )

    create constraint(:ingestion_catalog_change_pending_targets, :catalog_change_state_link,
             check:
               "(state NOT IN ('queued', 'preview_ready') OR catalog_sync_run_id IS NOT NULL) AND (state NOT IN ('pending', 'settled', 'failed') OR recheck_at IS NULL)"
           )

    create index(:ingestion_catalog_change_pending_targets, [desc: :updated_at, desc: :id],
             name: "ingestion_catalog_change_pending_targets_admin_idx"
           )

    create index(:ingestion_catalog_change_pending_targets, [:catalog_sync_run_id],
             name: "ingestion_catalog_change_pending_targets_run_idx",
             where: "catalog_sync_run_id IS NOT NULL"
           )

    create index(
             :ingestion_catalog_change_pending_targets,
             [:source_system_id, :state, :recheck_at, :id],
             name: "ingestion_catalog_change_pending_targets_recheck_idx"
           )

    create index(
             :ingestion_catalog_change_pending_targets,
             [:source_system_id, :state, :quiet_until, :first_received_at, :id],
             name: "ingestion_catalog_change_pending_targets_due_idx"
           )

    create unique_index(
             :ingestion_catalog_change_pending_targets,
             [:source_system_id, :target_type, :target_id],
             name: "ingestion_catalog_change_pending_targets_key_uidx"
           )

    create table(:ingestion_catalog_change_signals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :signal_id, :uuid, null: false
      add :contract_version, :text, null: false
      add :payload_hash, :string, size: 64, null: false
      add :target_type, :text, null: false
      add :target_id, :bigint, null: false
      add :source_updated_at, :utc_datetime_usec, null: false
      add :reason, :text, null: false
      add :disposition, :text, null: false
      add :received_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_catalog_change_signals_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :pending_target_id,
          references(:ingestion_catalog_change_pending_targets,
            column: :id,
            name: "ingestion_catalog_change_signals_pending_target_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create constraint(:ingestion_catalog_change_signals, :catalog_change_signal_contract,
             check: "contract_version = '2026-07-20.v1'"
           )

    create constraint(:ingestion_catalog_change_signals, :catalog_change_signal_hash,
             check: "payload_hash ~ '^[a-f0-9]{64}$'"
           )

    create constraint(:ingestion_catalog_change_signals, :catalog_change_signal_target,
             check: "target_type IN ('event', 'product', 'variation') AND target_id > 0"
           )

    create constraint(:ingestion_catalog_change_signals, :catalog_change_signal_reason,
             check:
               "reason IN ('saved', 'metadata_changed', 'status_changed', 'trashed', 'restored', 'deleted')"
           )

    create constraint(:ingestion_catalog_change_signals, :catalog_change_signal_disposition,
             check: "disposition IN ('accepted', 'stale')"
           )

    create index(:ingestion_catalog_change_signals, [:inserted_at, :id],
             name: "ingestion_catalog_change_signals_inserted_idx"
           )

    create index(:ingestion_catalog_change_signals, [:pending_target_id, :inserted_at],
             name: "ingestion_catalog_change_signals_pending_inserted_idx"
           )

    create unique_index(:ingestion_catalog_change_signals, [:source_system_id, :signal_id],
             name: "ingestion_catalog_change_signals_source_signal_uidx"
           )
  end

  def down do
    drop constraint(
           :ingestion_catalog_change_signals,
           "ingestion_catalog_change_signals_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_catalog_change_signals,
           "ingestion_catalog_change_signals_pending_target_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_catalog_change_signals,
                     [:source_system_id, :signal_id],
                     name: "ingestion_catalog_change_signals_source_signal_uidx"
                   )

    drop_if_exists index(:ingestion_catalog_change_signals, [:pending_target_id, :inserted_at],
                     name: "ingestion_catalog_change_signals_pending_inserted_idx"
                   )

    drop_if_exists index(:ingestion_catalog_change_signals, [:inserted_at, :id],
                     name: "ingestion_catalog_change_signals_inserted_idx"
                   )

    drop table(:ingestion_catalog_change_signals)

    drop constraint(
           :ingestion_catalog_change_pending_targets,
           "ingestion_catalog_change_pending_targets_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_catalog_change_pending_targets,
           "ingestion_catalog_change_pending_targets_catalog_sync_run_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_catalog_change_pending_targets,
                     [:source_system_id, :target_type, :target_id],
                     name: "ingestion_catalog_change_pending_targets_key_uidx"
                   )

    drop_if_exists index(
                     :ingestion_catalog_change_pending_targets,
                     [:source_system_id, :state, :quiet_until, :first_received_at, :id],
                     name: "ingestion_catalog_change_pending_targets_due_idx"
                   )

    drop_if_exists index(
                     :ingestion_catalog_change_pending_targets,
                     [:source_system_id, :state, :recheck_at, :id],
                     name: "ingestion_catalog_change_pending_targets_recheck_idx"
                   )

    drop_if_exists index(:ingestion_catalog_change_pending_targets, [:catalog_sync_run_id],
                     name: "ingestion_catalog_change_pending_targets_run_idx"
                   )

    drop_if_exists index(
                     :ingestion_catalog_change_pending_targets,
                     [desc: :updated_at, desc: :id],
                     name: "ingestion_catalog_change_pending_targets_admin_idx"
                   )

    drop table(:ingestion_catalog_change_pending_targets)
  end
end
