defmodule EventSales.Repo.Migrations.Slice1450bTickeraAttendeeState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_tickera_event_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tickera_site_url, :text, null: false, default: "https://voelgoed.co.za"
      add :api_key_env_var, :text, null: false
      add :api_key_last4, :text
      add :active, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_event_sources_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_tickera_event_sources_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:ingestion_tickera_event_sources, [:api_key_env_var],
             name: "ingestion_tickera_event_sources_api_key_env_var_idx"
           )

    create index(:ingestion_tickera_event_sources, [:active],
             name: "ingestion_tickera_event_sources_active_idx"
           )

    create index(:ingestion_tickera_event_sources, [:source_system_id],
             name: "ingestion_tickera_event_sources_source_system_id_idx"
           )

    create index(:ingestion_tickera_event_sources, [:event_id],
             name: "ingestion_tickera_event_sources_event_id_idx"
           )

    create unique_index(:ingestion_tickera_event_sources, [:source_system_id, :event_id],
             name: "ingestion_tickera_event_sources_unique_source_event_index"
           )

    create table(:ingestion_tickera_attendee_sync_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :requested_via, :text, null: false, default: "manual"
      add :sync_mode, :text, null: false, default: "full"
      add :status, :text, null: false, default: "queued"
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :paused_until, :utc_datetime_usec
      add :pause_reason, :text
      add :last_error, :text
      add :current_page, :bigint, null: false, default: 1
      add :last_successful_page, :bigint, null: false, default: 0
      add :attendees_seen_count, :bigint, null: false, default: 0
      add :attendees_upserted_count, :bigint, null: false, default: 0
      add :attendees_failed_count, :bigint, null: false, default: 0
      add :duplicate_page_count, :bigint, null: false, default: 0
      add :errors_count, :bigint, null: false, default: 0
      add :last_page_count, :bigint
      add :last_page_signature, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tickera_event_source_id,
          references(:ingestion_tickera_event_sources,
            column: :id,
            name: "ingestion_tickera_attendee_sync_runs_tickera_event_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_attendee_sync_runs_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_tickera_attendee_sync_runs_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(:ingestion_tickera_attendee_sync_runs, [:tickera_event_source_id, :status],
             name: "ingestion_tickera_attendee_sync_runs_source_status_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:event_id, :status],
             name: "ingestion_tickera_attendee_sync_runs_event_status_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:inserted_at],
             name: "ingestion_tickera_attendee_sync_runs_inserted_at_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:status],
             name: "ingestion_tickera_attendee_sync_runs_status_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:source_system_id],
             name: "ingestion_tickera_attendee_sync_runs_source_system_id_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:event_id],
             name: "ingestion_tickera_attendee_sync_runs_event_id_idx"
           )

    create index(:ingestion_tickera_attendee_sync_runs, [:tickera_event_source_id],
             name: "ingestion_tickera_attendee_sync_runs_source_idx"
           )

    create table(:ingestion_tickera_attendee_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ticket_code, :text, null: false
      add :checksum, :text
      add :ticket_type_id, :bigint
      add :ticket_type, :text
      add :first_name, :text
      add :last_name, :text
      add :email, :text
      add :buyer_first, :text
      add :buyer_last, :text
      add :buyer_email, :text
      add :allowed_checkins, :bigint
      add :used_checkins, :bigint
      add :remaining_checkins, :bigint
      add :checked_in, :boolean
      add :payment_status, :text
      add :payment_date_raw, :text
      add :custom_fields, :map, null: false, default: %{}
      add :raw_source_hash, :text, null: false
      add :source_updated_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tickera_event_source_id,
          references(:ingestion_tickera_event_sources,
            column: :id,
            name: "ingestion_tickera_attendee_snapshots_tickera_event_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :tickera_attendee_sync_run_id,
          references(:ingestion_tickera_attendee_sync_runs,
            column: :id,
            name: "ingestion_tickera_attendee_snapshots_tickera_attendee_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_attendee_snapshots_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :event_id,
          references(:catalog_events,
            column: :id,
            name: "ingestion_tickera_attendee_snapshots_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(
             :ingestion_tickera_attendee_snapshots,
             [:tickera_event_source_id, :payment_status],
             name: "ingestion_tickera_attendee_snapshots_source_payment_idx"
           )

    create index(
             :ingestion_tickera_attendee_snapshots,
             [:tickera_event_source_id, :ticket_type_id],
             name: "ingestion_tickera_attendee_snapshots_source_ticket_type_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:event_id, :ticket_type_id],
             name: "ingestion_tickera_attendee_snapshots_event_ticket_type_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:last_seen_at],
             name: "ingestion_tickera_attendee_snapshots_last_seen_at_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:payment_status],
             name: "ingestion_tickera_attendee_snapshots_payment_status_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:ticket_type_id],
             name: "ingestion_tickera_attendee_snapshots_ticket_type_id_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:checksum],
             name: "ingestion_tickera_attendee_snapshots_checksum_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:ticket_code],
             name: "ingestion_tickera_attendee_snapshots_ticket_code_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:source_system_id],
             name: "ingestion_tickera_attendee_snapshots_source_system_id_idx"
           )

    create index(:ingestion_tickera_attendee_snapshots, [:event_id],
             name: "ingestion_tickera_attendee_snapshots_event_id_idx"
           )

    create unique_index(
             :ingestion_tickera_attendee_snapshots,
             [:tickera_event_source_id, :ticket_code],
             name: "tickera_attendee_snapshots_source_ticket_code_idx"
           )
  end

  def down do
    drop constraint(
           :ingestion_tickera_attendee_snapshots,
           "ingestion_tickera_attendee_snapshots_tickera_event_source_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_attendee_snapshots,
           "ingestion_tickera_attendee_snapshots_tickera_attendee_sync_run_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_attendee_snapshots,
           "ingestion_tickera_attendee_snapshots_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_attendee_snapshots,
           "ingestion_tickera_attendee_snapshots_event_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_tickera_attendee_snapshots,
                     [:tickera_event_source_id, :ticket_code],
                     name: "tickera_attendee_snapshots_source_ticket_code_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:event_id],
                     name: "ingestion_tickera_attendee_snapshots_event_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:source_system_id],
                     name: "ingestion_tickera_attendee_snapshots_source_system_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:ticket_code],
                     name: "ingestion_tickera_attendee_snapshots_ticket_code_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:checksum],
                     name: "ingestion_tickera_attendee_snapshots_checksum_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:ticket_type_id],
                     name: "ingestion_tickera_attendee_snapshots_ticket_type_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:payment_status],
                     name: "ingestion_tickera_attendee_snapshots_payment_status_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:last_seen_at],
                     name: "ingestion_tickera_attendee_snapshots_last_seen_at_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_snapshots, [:event_id, :ticket_type_id],
                     name: "ingestion_tickera_attendee_snapshots_event_ticket_type_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_attendee_snapshots,
                     [:tickera_event_source_id, :ticket_type_id],
                     name: "ingestion_tickera_attendee_snapshots_source_ticket_type_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_attendee_snapshots,
                     [:tickera_event_source_id, :payment_status],
                     name: "ingestion_tickera_attendee_snapshots_source_payment_idx"
                   )

    drop table(:ingestion_tickera_attendee_snapshots)

    drop constraint(
           :ingestion_tickera_attendee_sync_runs,
           "ingestion_tickera_attendee_sync_runs_tickera_event_source_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_attendee_sync_runs,
           "ingestion_tickera_attendee_sync_runs_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_attendee_sync_runs,
           "ingestion_tickera_attendee_sync_runs_event_id_fkey"
         )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:tickera_event_source_id],
                     name: "ingestion_tickera_attendee_sync_runs_source_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:event_id],
                     name: "ingestion_tickera_attendee_sync_runs_event_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:source_system_id],
                     name: "ingestion_tickera_attendee_sync_runs_source_system_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:status],
                     name: "ingestion_tickera_attendee_sync_runs_status_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:inserted_at],
                     name: "ingestion_tickera_attendee_sync_runs_inserted_at_idx"
                   )

    drop_if_exists index(:ingestion_tickera_attendee_sync_runs, [:event_id, :status],
                     name: "ingestion_tickera_attendee_sync_runs_event_status_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_attendee_sync_runs,
                     [:tickera_event_source_id, :status],
                     name: "ingestion_tickera_attendee_sync_runs_source_status_idx"
                   )

    drop table(:ingestion_tickera_attendee_sync_runs)

    drop constraint(
           :ingestion_tickera_event_sources,
           "ingestion_tickera_event_sources_source_system_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_event_sources,
           "ingestion_tickera_event_sources_event_id_fkey"
         )

    drop_if_exists unique_index(:ingestion_tickera_event_sources, [:source_system_id, :event_id],
                     name: "ingestion_tickera_event_sources_unique_source_event_index"
                   )

    drop_if_exists index(:ingestion_tickera_event_sources, [:event_id],
                     name: "ingestion_tickera_event_sources_event_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_event_sources, [:source_system_id],
                     name: "ingestion_tickera_event_sources_source_system_id_idx"
                   )

    drop_if_exists index(:ingestion_tickera_event_sources, [:active],
                     name: "ingestion_tickera_event_sources_active_idx"
                   )

    drop_if_exists index(:ingestion_tickera_event_sources, [:api_key_env_var],
                     name: "ingestion_tickera_event_sources_api_key_env_var_idx"
                   )

    drop table(:ingestion_tickera_event_sources)
  end
end
