defmodule EventSales.Repo.Migrations.M300BackfillStartAuthority do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_events) do
      add :source_created_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:catalog_events) do
      remove :source_created_at
    end
  end
end
