defmodule EventSales.Repo.Migrations.M3F1HistoricalOrderMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_historical_order_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_order_id, :bigint, null: false
      add :manifest_source_created_at, :utc_datetime_usec, null: false
      add :manifest_source_modified_at, :utc_datetime_usec, null: false
      add :last_source_modified_at, :utc_datetime_usec, null: false
      add :event_match_state, :text, null: false, default: "non_target"
      add :resolution_state, :text, null: false, default: "manifest_resolved"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sync_run_id,
          references(:ingestion_sync_runs,
            column: :id,
            name: "ingestion_historical_order_memberships_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:ingestion_historical_order_memberships, [:sync_run_id, :source_order_id],
             name: "ingestion_historical_order_memberships_unique_run_order_index"
           )
  end

  def down do
    drop constraint(
           :ingestion_historical_order_memberships,
           "ingestion_historical_order_memberships_sync_run_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_historical_order_memberships,
                     [:sync_run_id, :source_order_id],
                     name: "ingestion_historical_order_memberships_unique_run_order_index"
                   )

    drop table(:ingestion_historical_order_memberships)
  end
end
