defmodule EventSales.Repo.Migrations.PreM502dEventSnapshotV2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:analytics_event_aggregate_snapshots, [:event_id],
                     name: "analytics_event_aggregate_snapshots_unique_event_index"
                   )

    alter table(:analytics_event_aggregate_snapshots) do
      add :gross_ticket_quantity, :bigint, null: false, default: 0
      add :refund_ticket_quantity, :bigint, null: false, default: 0
      add :gross_ticket_value, :decimal, null: false, default: "0"
      add :refund_ticket_value, :decimal, null: false, default: "0"
      add :recognised_order_count, :bigint, null: false, default: 0
    end

    create unique_index(:analytics_event_aggregate_snapshots, [:event_id, :currency],
             name: "analytics_event_aggregate_snapshots_unique_event_currency_index"
           )
  end

  def down do
    drop_if_exists unique_index(:analytics_event_aggregate_snapshots, [:event_id, :currency],
                     name: "analytics_event_aggregate_snapshots_unique_event_currency_index"
                   )

    alter table(:analytics_event_aggregate_snapshots) do
      remove :recognised_order_count
      remove :refund_ticket_value
      remove :gross_ticket_value
      remove :refund_ticket_quantity
      remove :gross_ticket_quantity
    end

    create unique_index(:analytics_event_aggregate_snapshots, [:event_id],
             name: "analytics_event_aggregate_snapshots_unique_event_index"
           )
  end
end
