defmodule EventSales.Repo.Migrations.Vs26e2CatalogAutoApply do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("SET LOCAL lock_timeout = '5s'")
    execute("SET LOCAL statement_timeout = '60s'")

    create table(:ingestion_tickera_catalog_auto_apply_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton_key, :text, null: false, default: "global"
      add :global_mode, :text, null: false, default: "disabled"
      add :enabled_policy_versions, {:array, :text}, null: false, default: []

      add :supported_snapshot_versions, {:array, :text},
        null: false,
        default: ["tickera_catalog_plan.v2"]

      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ingestion_tickera_catalog_auto_apply_configs, [:singleton_key],
             name: "tickera_auto_apply_config_singleton_idx"
           )

    create table(:ingestion_tickera_catalog_auto_apply_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :dry_run_hash, :text, null: false
      add :snapshot_schema_version, :text, null: false
      add :policy_version, :text, null: false
      add :decision_result, :text, null: false
      add :enqueue_state, :text, null: false, default: "not_applicable"
      add :apply_audit_state, :text, null: false, default: "not_started"
      add :reason_codes, {:array, :text}, null: false, default: []
      add :finding_summary, :map, null: false, default: %{}
      add :action_summary, :map, null: false, default: %{}
      add :historical_summary, :map, null: false, default: %{}
      add :origin, :text, null: false
      add :evaluated_global_mode, :text, null: false
      add :evaluated_source_mode, :text, null: false
      add :effective_mode, :text, null: false
      add :configuration_revision, :bigint, null: false
      add :configuration_fingerprint, :text, null: false
      add :enqueue_key, :text
      add :enqueue_attempts, :bigint, null: false, default: 0
      add :next_attempt_at, :utc_datetime_usec
      add :apply_job_id, :bigint
      add :evaluated_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :catalog_sync_run_id,
          references(:ingestion_tickera_catalog_sync_runs,
            column: :id,
            name: "ingestion_tickera_catalog_auto_apply_decisions_catalog_sync_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :source_system_id,
          references(:catalog_source_systems,
            column: :id,
            name: "ingestion_tickera_catalog_auto_apply_decisions_source_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:policy_version, :snapshot_schema_version, :evaluated_at],
             name: "tickera_catalog_auto_apply_decisions_policy_audit_idx"
           )

    create index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:next_attempt_at, :source_system_id, :id],
             name: "tickera_catalog_auto_apply_decisions_recovery_idx",
             where: "enqueue_state IN ('pending', 'claimed', 'retryable_failure')"
           )

    create index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:source_system_id, :inserted_at, :id],
             name: "tickera_catalog_auto_apply_decisions_source_recent_idx"
           )

    create index(:ingestion_tickera_catalog_auto_apply_decisions, [:apply_job_id],
             name: "tickera_catalog_auto_apply_decisions_apply_job_uidx",
             unique: true,
             where: "apply_job_id IS NOT NULL"
           )

    create index(:ingestion_tickera_catalog_auto_apply_decisions, [:enqueue_key],
             name: "tickera_catalog_auto_apply_decisions_enqueue_key_uidx",
             unique: true
           )

    create unique_index(
             :ingestion_tickera_catalog_auto_apply_decisions,
             [:catalog_sync_run_id, :dry_run_hash, :policy_version],
             name: "tickera_auto_apply_decision_identity_idx"
           )

    alter table(:ingestion_tickera_catalog_sync_runs) do
      add :origin, :text, default: "legacy_unknown"
    end

    execute("""
    DO $$
    DECLARE
      updated_rows integer;
    BEGIN
      LOOP
        WITH batch AS (
          SELECT id
          FROM ingestion_tickera_catalog_sync_runs
          WHERE origin IS NULL
          ORDER BY id
          LIMIT 1000
          FOR UPDATE SKIP LOCKED
        )
        UPDATE ingestion_tickera_catalog_sync_runs AS runs
        SET origin = 'legacy_unknown'
        FROM batch
        WHERE runs.id = batch.id;

        GET DIAGNOSTICS updated_rows = ROW_COUNT;
        EXIT WHEN updated_rows = 0;
      END LOOP;
    END
    $$;
    """)

    alter table(:ingestion_tickera_catalog_sync_runs) do
      modify :origin, :text, null: false, default: "legacy_unknown", from: {:text, null: true}
    end

    alter table(:catalog_source_systems) do
      add :catalog_auto_apply_mode, :text, null: false, default: "inherit"
      add :catalog_auto_apply_allowlisted, :boolean, null: false, default: false
    end

    create constraint(
             :ingestion_tickera_catalog_auto_apply_configs,
             :tickera_catalog_auto_apply_configs_singleton_key_check,
             check: """
               singleton_key = 'global'
             """
           )

    create constraint(
             :ingestion_tickera_catalog_auto_apply_configs,
             :tickera_catalog_auto_apply_configs_revision_check,
             check: """
               revision >= 1
             """
           )

    create constraint(:ingestion_tickera_catalog_sync_runs, :catalog_sync_runs_origin_check,
             check: "origin IN ('human_admin', 'targeted_catalog_change', 'legacy_unknown')"
           )

    create constraint(:catalog_source_systems, :source_systems_auto_apply_mode_check,
             check: "catalog_auto_apply_mode IN ('inherit', 'disabled', 'observe', 'enabled')"
           )

    create constraint(
             :ingestion_tickera_catalog_auto_apply_configs,
             :tickera_catalog_auto_apply_configs_global_mode_check,
             check: "global_mode IN ('disabled', 'observe', 'enabled')"
           )

    create constraint(
             :ingestion_tickera_catalog_auto_apply_decisions,
             :tickera_catalog_auto_apply_decisions_state_check,
             check: """
             decision_result IN ('observe', 'eligible', 'ineligible')
             AND enqueue_state IN ('not_applicable', 'pending', 'claimed', 'enqueued', 'retryable_failure', 'terminal_failure', 'superseded')
             AND apply_audit_state IN ('not_started', 'claim_rejected', 'claimed', 'completed', 'failed')
             AND origin IN ('human_admin', 'targeted_catalog_change', 'legacy_unknown')
             AND evaluated_global_mode IN ('disabled', 'observe', 'enabled')
             AND evaluated_source_mode IN ('inherit', 'disabled', 'observe', 'enabled')
             AND effective_mode IN ('disabled', 'observe', 'enabled')
             """
           )

    create constraint(
             :ingestion_tickera_catalog_auto_apply_decisions,
             :tickera_catalog_auto_apply_decisions_format_check,
             check: """
             dry_run_hash ~ '^[0-9a-f]{64}$'
             AND configuration_fingerprint ~ '^[0-9a-f]{64}$'
             AND snapshot_schema_version ~ '^[a-z0-9][a-z0-9._-]{0,79}$'
             AND policy_version ~ '^[a-z0-9][a-z0-9._-]{0,79}$'
             AND enqueue_attempts BETWEEN 0 AND 20
             AND cardinality(reason_codes) <= 32
             """
           )

    create constraint(
             :ingestion_tickera_catalog_auto_apply_decisions,
             :tickera_catalog_auto_apply_decisions_linkage_check,
             check: """
             (enqueue_state <> 'enqueued' OR apply_job_id IS NOT NULL)
             AND (enqueue_state <> 'not_applicable' OR apply_job_id IS NULL)
             AND (enqueue_state NOT IN ('terminal_failure', 'superseded') OR next_attempt_at IS NULL)
             AND octet_length(finding_summary::text) <= 1024
             AND octet_length(action_summary::text) <= 1024
             AND octet_length(historical_summary::text) <= 2048
             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     :tickera_catalog_auto_apply_decisions_linkage_check
                   )

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     :tickera_catalog_auto_apply_decisions_format_check
                   )

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     :tickera_catalog_auto_apply_decisions_state_check
                   )

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_configs,
                     :tickera_catalog_auto_apply_configs_global_mode_check
                   )

    drop_if_exists constraint(:catalog_source_systems, :source_systems_auto_apply_mode_check)

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_sync_runs,
                     :catalog_sync_runs_origin_check
                   )

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_configs,
                     :tickera_catalog_auto_apply_configs_revision_check
                   )

    drop_if_exists constraint(
                     :ingestion_tickera_catalog_auto_apply_configs,
                     :tickera_catalog_auto_apply_configs_singleton_key_check
                   )

    alter table(:catalog_source_systems) do
      remove :catalog_auto_apply_allowlisted
      remove :catalog_auto_apply_mode
    end

    alter table(:ingestion_tickera_catalog_sync_runs) do
      remove :origin
    end

    drop constraint(
           :ingestion_tickera_catalog_auto_apply_decisions,
           "ingestion_tickera_catalog_auto_apply_decisions_catalog_sync_run_id_fkey"
         )

    drop constraint(
           :ingestion_tickera_catalog_auto_apply_decisions,
           "ingestion_tickera_catalog_auto_apply_decisions_source_system_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:catalog_sync_run_id, :dry_run_hash, :policy_version],
                     name: "tickera_auto_apply_decision_identity_idx"
                   )

    drop_if_exists index(:ingestion_tickera_catalog_auto_apply_decisions, [:enqueue_key],
                     name: "tickera_catalog_auto_apply_decisions_enqueue_key_uidx"
                   )

    drop_if_exists index(:ingestion_tickera_catalog_auto_apply_decisions, [:apply_job_id],
                     name: "tickera_catalog_auto_apply_decisions_apply_job_uidx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:source_system_id, :inserted_at, :id],
                     name: "tickera_catalog_auto_apply_decisions_source_recent_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:next_attempt_at, :source_system_id, :id],
                     name: "tickera_catalog_auto_apply_decisions_recovery_idx"
                   )

    drop_if_exists index(
                     :ingestion_tickera_catalog_auto_apply_decisions,
                     [:policy_version, :snapshot_schema_version, :evaluated_at],
                     name: "tickera_catalog_auto_apply_decisions_policy_audit_idx"
                   )

    drop table(:ingestion_tickera_catalog_auto_apply_decisions)

    drop_if_exists unique_index(:ingestion_tickera_catalog_auto_apply_configs, [:singleton_key],
                     name: "tickera_auto_apply_config_singleton_idx"
                   )

    drop table(:ingestion_tickera_catalog_auto_apply_configs)
  end
end
