defmodule EventSales.Repo.Migrations.M304aFinancialSourcePrimitives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_order_items) do
      add :line_total_tax, :decimal
    end

    alter table(:sales_orders) do
      add :paid_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:sales_orders) do
      remove :paid_at
    end

    alter table(:sales_order_items) do
      remove :line_total_tax
    end
  end
end
