defmodule EventSales.Repo.Migrations.Slice17CsvApplyWorker do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_csv_import_rows) do
      add :applied_at, :utc_datetime_usec
    end

    alter table(:ingestion_csv_import_batches) do
      add :applied_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:ingestion_csv_import_batches) do
      remove :applied_at
    end

    alter table(:ingestion_csv_import_rows) do
      remove :applied_at
    end
  end
end
