defmodule EventSales.Repo.Migrations.M3F2RefundReferenceProof do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_historical_refund_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference_count, :bigint, null: false, default: 0
      add :observed_at, :utc_datetime_usec, null: false
      add :resolution_state, :text, null: false, default: "manifest_resolved"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :historical_order_membership_id,
          references(:ingestion_historical_order_memberships,
            column: :id,
            name: "ingestion_historical_refund_observations_historical_order_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(
             :ingestion_historical_refund_observations,
             [:historical_order_membership_id],
             name: "hist_refund_observations_membership_idx"
           )

    create table(:ingestion_historical_refund_references, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :woo_refund_id, :bigint, null: false
      add :source_state, :text, null: false, default: "present"
      add :last_observed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :historical_refund_observation_id,
          references(:ingestion_historical_refund_observations,
            column: :id,
            name: "ingestion_historical_refund_references_historical_refund_observation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(
             :ingestion_historical_refund_references,
             [:historical_refund_observation_id, :woo_refund_id],
             name: "hist_refund_refs_observation_refund_idx"
           )
  end

  def down do
    drop constraint(
           :ingestion_historical_refund_references,
           "ingestion_historical_refund_references_historical_refund_observation_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_historical_refund_references,
                     [:historical_refund_observation_id, :woo_refund_id],
                     name: "hist_refund_refs_observation_refund_idx"
                   )

    drop table(:ingestion_historical_refund_references)

    drop constraint(
           :ingestion_historical_refund_observations,
           "ingestion_historical_refund_observations_historical_order_membership_id_fkey"
         )

    drop_if_exists unique_index(
                     :ingestion_historical_refund_observations,
                     [:historical_order_membership_id],
                     name: "hist_refund_observations_membership_idx"
                   )

    drop table(:ingestion_historical_refund_observations)
  end
end
