defmodule EventSales.Repo.Migrations.AshBaselineExtensionProofs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_baseline_state_machine_proofs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :state, :text, null: false, default: "draft"
    end

    create table(:ash_baseline_paper_trail_proofs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ash_baseline_paper_trail_proof_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:ash_baseline_paper_trail_proofs,
            column: :id,
            name: "ash_baseline_paper_trail_proof_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(
           :ash_baseline_paper_trail_proof_versions,
           "ash_baseline_paper_trail_proof_versions_version_source_id_fkey"
         )

    drop table(:ash_baseline_paper_trail_proof_versions)

    drop table(:ash_baseline_paper_trail_proofs)

    drop table(:ash_baseline_state_machine_proofs)
  end
end
